language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
# - bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key: 96961756-75ea-48bc-bb73-34c1307f5d0c
  app:
  run: rails db:migrate
